### PR TITLE
Add `--no-output-files` option

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
Permits a user to override output options in Brakeman config from command line, and run Brakeman without writing files to system.

This change lets Code Climate run with a line-item ignore of that part of a user's Brakeman config.

Running by @codeclimate-community/cc-staff for initial review

### CODE REVIEW

**Comment by ABaldwinHunter** [comment]
P.S. Alternatively, we could [always ignore output files](https://github.com/presidentbeef/brakeman/compare/master...codeclimate-community:abh-codeclimate-ignore-fileoutput?expand=1) for Code Climate format only.

Pros: less invasive
Cons: limit flexibility of `--format codeclimate` and omit a perhaps useful option for brakeman

**Comment by jpignata** [comment]
@ABaldwinHunter Since command line parameters override configuration options, we can fix this more easily by adding `--output /dev/stdout` to `bin/codeclimate-brakeman`.

**Comment by ABaldwinHunter** [comment]
@jpignata Thanks! Great solution. I didn't realize that the command line options would completely wipe out those in config.

Closing this PR.

I still saw 
```
Running brakeman: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine brakeman failed with status 1 and stderr 
/usr/src/app/lib/brakeman.rb:363:in `initialize': Permission denied @ rb_sysopen - /dev/stdout (Errno::EACCES)
	from /usr/src/app/lib/brakeman.rb:363:in `open'
	from /usr/src/app/lib/brakeman.rb:363:in `block in write_report_to_files'
	from /usr/src/app/lib/brakeman.rb:362:in `each'
	from /usr/src/app/lib/brakeman.rb:362:in `each_with_index'
	from /usr/src/app/lib/brakeman.rb:362:in `write_report_to_files'
	from /usr/src/app/lib/brakeman.rb:351:in `scan'
```

so might fiddle with getting the perfect incantation.

**Comment by jpignata** [comment]
@ABaldwinHunter Hmm. I tested it before I suggested it and it worked for me. This makes me wonder if we're running into a behavior difference between versions of the Docker engine. I'm running Docker 1.9.

**Comment by jpignata** [comment]
Seems likely you're running <1.9: https://github.com/opencontainers/runc/pull/280

I'm not sure what version we officially support but it's moot since we're running 1.8 ourselves in production. I suspect we may be able to work around this in the Dockerfile of the engine for now.

**Pull request closed without merging**
